development:
  host: localhost
  port: 6379
  nodes: [
    {host: 127.0.0.1, port: 6379},
    {host: 127.0.0.1, port: 6380},
  ]
test:
  host: localhost
  port: 6379
  nodes: [
    {host: 127.0.0.1, port: 6379},
    {host: 127.0.0.1, port: 6380},
  ]
